/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package testPackage;
import control.DBHandler;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.CalendarItem;
/**
 *
 * @author Nikolaj
 */
public class CalendarPanelTest extends javax.swing.JPanel {
    private DBHandler dbHandler;
    private DefaultListModel calendarItemListModel;
    /**
     * Creates new form CalendarPanelTest
     */
    public CalendarPanelTest(DBHandler dbHandler) throws SQLException{
        calendarItemListModel = new DefaultListModel();
        this.dbHandler = dbHandler;
        loadCalendarItems();
        initComponents();
    }

    
    private void loadCalendarItems() throws SQLException{
          int oldSelection = -1;
                try {
           oldSelection =  calendarItemList.getSelectedIndex();
            calendarItemList.clearSelection();

        } catch (NullPointerException ex) {
            System.out.println("Vi ved der kommer en null point exception ved CalendarItem første gang den kører.");
        }
        calendarItemListModel.clear();
        System.out.println("1!");
        ArrayList<CalendarItem> calendarItems = dbHandler.retrieveAllCalendarItems();
        System.out.println("size = " +calendarItems.size());
        
        for (int i = 0; i < calendarItems.size(); i++) {
            calendarItemListModel.addElement(calendarItems.get(i));
            System.out.println("2!");
        }
        if (oldSelection >= 0) {
            System.out.println("3!");
            calendarItemList.setSelectedIndex(oldSelection);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        calendarItemList = new javax.swing.JList(calendarItemListModel);

        jScrollPane1.setViewportView(calendarItemList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList calendarItemList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
