/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.SKS_Headline;

/**
 *
 * @author Kasper
 */
public class SKS_headlinePanel extends javax.swing.JPanel {
private int height;
    /**
     * Creates new form SKS_headlinePanel
     */
  public SKS_headlinePanel(SKS_Headline headline) {
        initComponents();
        headlineLable.setText(headline.getHeadline());
        height = 0;
        for (int i = 0; i < headline.getQuestions().size(); i++) {
            SKS_questionPanel sksquestion = new SKS_questionPanel(headline.getQuestions().get(i));
            sksquestion.setVisible(true);
            height = height+35;
            System.out.println("x:"+height+"i:"+i);
            sksquestion.setBounds(0, height, 600, 25);
            add(sksquestion);
        //    setSize(700, height);
        }
        System.out.println("PanelHeight"+height+" i:"+headline.getQuestions().size());
       // setSize(700, height);
    }
  
  public int getCurrentHeight(){
     return height;
  }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headlineLable = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 100));

        headlineLable.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headlineLable, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headlineLable, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headlineLable;
    // End of variables declaration//GEN-END:variables
}
